### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by tuzhirun** [abhichand26/v-SVR-using-brain-storm-optimization#1]
Can you share the data set? Thank you!

**Comment by abhichand26** [comment]
Data set can be downloaded from here:
https://finance.yahoo.com/quote/XCHA.DE/history?p=XCHA.DE

**Comment by abhichand26** [comment]
> Can you share the data set? Thank you!

Data set can be downloaded from here:
https://finance.yahoo.com/quote/XCHA.DE/history?p=XCHA.DE
